# Load plugins
source "%val{config}/powerline-modified-solarized.kak"
source "%val{config}/plugins.kak"

# Configuration options
set -add global autoinfo normal
set -add global ui_options ncurses_assistant=none
colorscheme solarized-light-modified
add-highlighter global/ number-lines -separator " "
add-highlighter global/ show-whitespaces -spc ' '
set-option global tabstop 2
set-option global indentwidth 2
set-option global ui_options ncurses_status_on_top=yes

# Key mappings
map global normal <c-p> ': fzf-mode<ret>'

