# Load plugins
source "%val{config}/plugins.kak"

# Configuration options
colorscheme selenized-light-modified
add-highlighter global/ number-lines -separator " "
add-highlighter global/ show-whitespaces -spc ' '
set-option -add global autoinfo normal
set-option -add global tabstop 2
set-option -add global indentwidth 2
set-option -add global ui_options terminal_assistant=none

# Key mappings
map -docstring 'fzf' global user p ':fzf-mode<ret>'
map -docstring 'lf'  global user l ':lf<ret>'
map -docstring 'Wrap to 100 columns' global user W '|fmt --width 100<ret>'

declare-user-mode tig
map global tig b ':tmux-terminal-vertical tig blame %val{buffile}<ret>:nop %sh{tmux resizep -Z}<ret>' -docstring 'show git status (with tig)'
map global tig s ':tmux-terminal-vertical tig status<ret>:nop %sh{tmux resizep -Z}<ret>' -docstring 'show git status (with tig)'
map global tig m ':tmux-terminal-vertical tig<ret>:nop %sh{tmux resizep -Z}<ret>' -docstring 'show git status (with tig)'
map global user t ': enter-user-mode tig<ret>' -docstring 'tig commands'

