# jq
[grammar.jq.source.git]
url = "https://github.com/flurie/tree-sitter-jq"
pin = "c204e36d2c3c6fce1f57950b12cabcc24e5cc4d9"

[grammar.jq]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "jq.so"]
link_flags = ["-O3"]

[language.jq.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "3beb268068d23294a26b47eab43b0a13a2a3a951"

[language.jq.queries]
path = "runtime/queries/jq"

